### ISSUE TITLE
Performance of the Network

### ISSUE THREAD

**Issue by Arman001** [DreamingRaven/python-fhez#12]
Hi!
I had to download Fashion MNIST Dataset manually and then place it inside to train the network as there was an unzipping problem. I reached about 62% accuracy on this. Previous results here are also showing same kind of accuracy. Can you kindly tell me that is this the performance you are getting ? and is it fine?
Thank you.

**Comment by DreamingRaven** [comment]
@Arman001 oh that's interesting, what was wrong with the unzipping? Was there something in particular that was problematic? The source server did have some downtime recently so apologies if that cause you any issues, but i'm glad you could download it manually to use instead. Yeah around 62% for such as small network is expected, it is a mere 1 layer CNN with direct ANN so we would expect it to get this kind of performance. There is nothing stopping you from adding more CNN layers or whatever else you would like to create a more complex network to learn slightly more complex relationships than this initial network does.

Apologies in the delay, I am at a conference today and tomorrow and I only just now had some time to response so my apologies. Let me know if you have any other issues too, i'm curious to see other people using my work, and I know there will still be many bugs. But if you let me know about them I can probably fix them very quickly, and write tests so they don't come up again!

**Comment by Arman001** [comment]
Thank you for your reply and it was pretty fast.  
**Issue with the unzip**
It is just saying about the path given that it is not a zip file so I put datasets manually there.
**Working of the model**
You are right about that it is one layered model and I am sorry I was expecting to give the accuracy to me a like normal 1 layer custom built model. I think main thing is here the model is trained with your own structure build for the encrypted process also.
**Your work**
You have really put a lot of effort in here and EDLaaS is a very fine work. I am also working on my MS Thesis in encrypted deep learning, so I will be looking on your work and bothering you more. :)

**Comment by DreamingRaven** [comment]
No problem, let me know when you have any issue! Or if anything is unclear so I can sort it and help you + others. Good luck with your studies!

**Comment by Arman001** [comment]
@DreamingRaven Thank you very much.
